/* GTK 4 / libadwaita — generated by Omarchy from the active theme's colors.toml.
 *
 * Omarchy ships no GTK template, so GTK apps (Nautilus, and every other
 * libadwaita app) render in stock Adwaita regardless of the active theme.
 * This user template fills that gap: omarchy-theme-set-templates globs
 * ~/.config/omarchy/themed/*.tpl, so every theme — stock ones included —
 * now generates a gtk.css alongside its ghostty.conf and btop.theme.
 *
 * ~/.config/gtk-4.0/gtk.css symlinks to the generated file in
 * ~/.local/state/omarchy/current/theme/, so it follows the active theme.
 * GTK reads CSS at startup: restart an app to pick up a theme change.
 *
 * libadwaita 1.6+ reads the :root custom properties; @define-color is the
 * older mechanism, still honoured, and is what GTK3 apps understand. Both
 * are emitted so this works across versions.
 */

@define-color window_bg_color {{ background }};
@define-color window_fg_color {{ foreground }};
@define-color view_bg_color {{ dark_background }};
@define-color view_fg_color {{ foreground }};

@define-color headerbar_bg_color {{ lighter_background }};
@define-color headerbar_fg_color {{ foreground }};
@define-color headerbar_border_color {{ mix background foreground 14% }};
@define-color headerbar_backdrop_color {{ background }};
@define-color headerbar_shade_color {{ darker_background }};

@define-color sidebar_bg_color {{ mix background lighter_background 45% }};
@define-color sidebar_fg_color {{ foreground }};
@define-color sidebar_backdrop_color {{ background }};
@define-color sidebar_border_color {{ darker_background }};
@define-color sidebar_shade_color {{ darker_background }};

@define-color secondary_sidebar_bg_color {{ mix background lighter_background 25% }};
@define-color secondary_sidebar_fg_color {{ foreground }};
@define-color secondary_sidebar_backdrop_color {{ background }};
@define-color secondary_sidebar_border_color {{ darker_background }};
@define-color secondary_sidebar_shade_color {{ darker_background }};

@define-color card_bg_color {{ lighter_background }};
@define-color card_fg_color {{ foreground }};
@define-color card_shade_color {{ darker_background }};

@define-color dialog_bg_color {{ lighter_background }};
@define-color dialog_fg_color {{ foreground }};
@define-color popover_bg_color {{ lighter_background }};
@define-color popover_fg_color {{ foreground }};
@define-color popover_shade_color {{ darker_background }};

@define-color thumbnail_bg_color {{ lighter_background }};
@define-color thumbnail_fg_color {{ foreground }};
@define-color shade_color {{ darker_background }};
@define-color scrollbar_outline_color {{ muted }};

@define-color accent_bg_color {{ accent }};
@define-color accent_fg_color {{ background }};
@define-color accent_color {{ accent }};

@define-color destructive_bg_color {{ red }};
@define-color destructive_fg_color {{ background }};
@define-color destructive_color {{ red }};
@define-color success_bg_color {{ green }};
@define-color success_fg_color {{ background }};
@define-color success_color {{ green }};
@define-color warning_bg_color {{ yellow }};
@define-color warning_fg_color {{ background }};
@define-color warning_color {{ yellow }};
@define-color error_bg_color {{ red }};
@define-color error_fg_color {{ background }};
@define-color error_color {{ red }};

/* GTK3 names, for any non-libadwaita app pointed at this file. */
@define-color theme_bg_color {{ background }};
@define-color theme_fg_color {{ foreground }};
@define-color theme_base_color {{ dark_background }};
@define-color theme_text_color {{ foreground }};
@define-color theme_selected_bg_color {{ accent }};
@define-color theme_selected_fg_color {{ background }};
@define-color insensitive_bg_color {{ background }};
@define-color insensitive_fg_color {{ dark_foreground }};
@define-color borders {{ mix background foreground 16% }};

:root {
  --window-bg-color: {{ background }};
  --window-fg-color: {{ foreground }};
  --view-bg-color: {{ dark_background }};
  --view-fg-color: {{ foreground }};

  --headerbar-bg-color: {{ lighter_background }};
  --headerbar-fg-color: {{ foreground }};
  --headerbar-border-color: {{ mix background foreground 14% }};
  --headerbar-backdrop-color: {{ background }};
  --headerbar-shade-color: {{ darker_background }};

  --sidebar-bg-color: {{ mix background lighter_background 45% }};
  --sidebar-fg-color: {{ foreground }};
  --sidebar-backdrop-color: {{ background }};
  --sidebar-border-color: {{ darker_background }};
  --sidebar-shade-color: {{ darker_background }};

  --secondary-sidebar-bg-color: {{ mix background lighter_background 25% }};
  --secondary-sidebar-fg-color: {{ foreground }};
  --secondary-sidebar-backdrop-color: {{ background }};
  --secondary-sidebar-border-color: {{ darker_background }};
  --secondary-sidebar-shade-color: {{ darker_background }};

  --card-bg-color: {{ lighter_background }};
  --card-fg-color: {{ foreground }};
  --card-shade-color: {{ darker_background }};

  --dialog-bg-color: {{ lighter_background }};
  --dialog-fg-color: {{ foreground }};
  --popover-bg-color: {{ lighter_background }};
  --popover-fg-color: {{ foreground }};
  --popover-shade-color: {{ darker_background }};

  --thumbnail-bg-color: {{ lighter_background }};
  --thumbnail-fg-color: {{ foreground }};
  --shade-color: {{ darker_background }};
  --scrollbar-outline-color: {{ muted }};

  --accent-bg-color: {{ accent }};
  --accent-fg-color: {{ background }};
  --accent-color: {{ accent }};

  --destructive-bg-color: {{ red }};
  --destructive-fg-color: {{ background }};
  --destructive-color: {{ red }};
  --success-bg-color: {{ green }};
  --success-fg-color: {{ background }};
  --success-color: {{ green }};
  --warning-bg-color: {{ yellow }};
  --warning-fg-color: {{ background }};
  --warning-color: {{ yellow }};
  --error-bg-color: {{ red }};
  --error-fg-color: {{ background }};
  --error-color: {{ red }};
}
